repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude_types: [json]

- repo: https://github.com/kynan/nbstripout
  rev: "0.5.0"
  hooks:
  - id: nbstripout

- repo: https://github.com/mwouts/jupytext
  rev: v1.13.4
  hooks:
  - id: jupytext
    files: |
      (?x)^(docs/tutorials/.*\.ipynb)$
    args: [--pipe, black]
    additional_dependencies:
      - black
