repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude_types: [json]

- repo: https://github.com/mwouts/jupytext
  rev: v1.11.2
  hooks:
  - id: jupytext
    files: |
      (?x)^(docs/tutorials/.*\.md)$
    args: [--pipe, black]
    additional_dependencies:
      - black
